# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20160213_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotfunction',
            name='options',
            field=models.ManyToManyField(blank=True, to='charts.Option'),
        ),
        migrations.AlterField(
            model_name='plotfunction',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='charts.Parameter'),
        ),
    ]
