# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20160213_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotfunction',
            name='plot1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plotfunction',
            name='plot2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plotfunction',
            name='plot3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plotfunction',
            name='plot4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
