# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20160215_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='plotfunction',
            name='plot1',
        ),
        migrations.RemoveField(
            model_name='plotfunction',
            name='plot2',
        ),
        migrations.RemoveField(
            model_name='plotfunction',
            name='plot3',
        ),
        migrations.RemoveField(
            model_name='plotfunction',
            name='plot4',
        ),
        migrations.AddField(
            model_name='plotimage',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.PlotFunction'),
        ),
    ]
