# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20160215_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parameterchoice',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
